main: com.rooxchicken.overload.Overload
name: OverloadPlugin
version: 0.1
api-version: '1.20'

commands:
   setstars:
      description: Sets your current stars
      usage: /setstars <number>
   withdraw:
      description: Withdraws a star
      usage: /withdraw
   giveitems:
      description: Gives the items
      usage: /giveitems